<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\spica\node_modules\**" />
    <None Include="wwwroot\spica\node_modules\**" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
  </ItemGroup>

</Project>
